
daily.sh at 2022-08-24T16:00:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:01:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:02:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:03:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:04:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:05:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:06:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:07:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:09:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2b4adc1db0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b4adc1db0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 926, in execute_stream
    return super().execute_stream(post=post)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/utils/decorators.py", line 9, in wrapper
    raw = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 191, in execute_stream
    response = self.submit(post=post)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 959, in submit
    response = self._session.post(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b4adc1db0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 245, in execute_votable
    raise DALFormatError(e, self.queryurl)
pyvo.dal.exceptions.DALFormatError: ConnectionError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b4adc1db0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

git add * in /home/lachaume/git/autolog
git commit
git push
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


git add * in /data/www/twoptwo.com

daily.sh at 2022-08-24T16:11:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:12:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe10287f220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe10287f220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 926, in execute_stream
    return super().execute_stream(post=post)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/utils/decorators.py", line 9, in wrapper
    raw = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 191, in execute_stream
    response = self.submit(post=post)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 959, in submit
    response = self._session.post(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe10287f220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 245, in execute_votable
    raise DALFormatError(e, self.queryurl)
pyvo.dal.exceptions.DALFormatError: ConnectionError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe10287f220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

git add * in /home/lachaume/git/autolog
git commit
git push
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


git add * in /data/www/twoptwo.com
git commit
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc2a084cf10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2a084cf10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 926, in execute_stream
    return super().execute_stream(post=post)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/utils/decorators.py", line 9, in wrapper
    raw = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 191, in execute_stream
    response = self.submit(post=post)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 959, in submit
    response = self._session.post(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2a084cf10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 245, in execute_votable
    raise DALFormatError(e, self.queryurl)
pyvo.dal.exceptions.DALFormatError: ConnectionError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2a084cf10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

daily.sh at 2022-08-24T16:31:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

github pull in /data/www/twoptwo.com
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f72a9d54100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72a9d54100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 926, in execute_stream
    return super().execute_stream(post=post)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/utils/decorators.py", line 9, in wrapper
    raw = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 191, in execute_stream
    response = self.submit(post=post)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 959, in submit
    response = self._session.post(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72a9d54100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 245, in execute_votable
    raise DALFormatError(e, self.queryurl)
pyvo.dal.exceptions.DALFormatError: ConnectionError: HTTPConnectionPool(host='archive.eso.org', port=80): Max retries exceeded with url: /tap_obs/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72a9d54100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   a83994c0..55d1679c  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2022-08-24T16:32:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:33:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:34:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:35:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:36:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:37:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:38:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:39:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:40:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
github pull in /home/lachaume/git/autolog

daily.sh at 2022-08-24T16:41:01-04:00
-------------------------------------


github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:42:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   55d1679c..a899381c  master -> master


git add * in /data/www/twoptwo.com
git commit
To github.com:loqueelvientoajuarez/2.2m-website.git
   7126680..2e53244  main -> main

github pull in /home/lachaume/git/autolog

daily.sh at 2022-08-24T16:43:01-04:00
-------------------------------------


github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   a899381c..9ffedb3f  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2022-08-24T16:44:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   9ffedb3f..82431c09  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2022-08-24T16:45:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:46:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   82431c09..c253f747  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2022-08-24T16:47:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   c253f747..1b782981  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2022-08-24T16:48:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:49:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   1b782981..5a1bdadb  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2022-08-24T16:50:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   5a1bdadb..945ce1bb  master -> master


git add * in /data/www/twoptwo.com
git commit

daily.sh at 2022-08-24T16:51:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog
Everything up-to-date


github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:52:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   945ce1bb..8a2aafcd  master -> master


git add * in /data/www/twoptwo.com
git commit

daily.sh at 2022-08-24T16:53:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com
To github.com:loqueelvientoajuarez/2.2m-website.git
   2e53244..048532c  main -> main


executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:54:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   8a2aafcd..70492356  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2022-08-24T16:55:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:56:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

git add * in /home/lachaume/git/autolog
git commit
git push

executing periodlog.py in /home/lachaume/git/autolog/scripts
To github.com:loqueelvientoajuarez/obslog.git
   70492356..eb817794  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date

github pull in /home/lachaume/git/autolog

daily.sh at 2022-08-24T16:57:01-04:00
-------------------------------------


github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   eb817794..c251e792  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   c251e792..bd31c23d  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2022-08-24T16:58:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2022-08-24T16:59:01-04:00
-------------------------------------

github pull in /home/lachaume/git/autolog

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   bd31c23d..bf02ca61  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   bf02ca61..98514d1a  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   98514d1a..47ab322d  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   47ab322d..932e55cf  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   932e55cf..3fbdc6e0  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   3fbdc6e0..794a431e  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   794a431e..29d8b268  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   29d8b268..fc74bf49  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   fc74bf49..fbfed2dc  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   fbfed2dc..f21e39a0  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
   f21e39a0..32d7377d  master -> master


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
