
daily.sh at 2023-03-13T16:00:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:01:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:02:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:03:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:04:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:05:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:06:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:07:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:08:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:09:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:10:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:11:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:12:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:13:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:14:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:15:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:16:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error
    for start, tag, data, pos in iterator:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
ValueError: 1:49: syntax error
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync


git add * in /home/lachaume/git/autolog
git add * in /home/lachaume/git/autolog
fatal: Unable to create '/home/lachaume/git/autolog/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git commit
fatal: Unable to create '/home/lachaume/git/autolog/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git push
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
git commit
Everything up-to-date

Everything up-to-date

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push

daily.sh at 2023-03-13T16:17:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit

executing periodlog.py in /home/lachaume/git/autolog/scripts
Everything up-to-date

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push

daily.sh at 2023-03-13T16:18:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:19:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:20:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push

executing periodlog.py in /home/lachaume/git/autolog/scripts
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push

daily.sh at 2023-03-13T16:21:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /data/www/twoptwo.com
git commit
Everything up-to-date

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

daily.sh at 2023-03-13T16:22:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

git add * in /home/lachaume/git/autolog
git commit
git push
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
git commit
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Everything up-to-date

Everything up-to-date

Everything up-to-date


git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
Everything up-to-date
git commit

Everything up-to-date

Everything up-to-date


daily.sh at 2023-03-13T16:23:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:24:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:25:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:26:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:27:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:28:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:29:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:30:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:31:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:32:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:33:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 242, in execute_votable
    return votableparse(self.execute_stream(post=post).read)
  File "/usr/local/lib/python3.10/dist-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/table.py", line 160, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/usr/local/lib/python3.10/dist-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lachaume/git/autolog/scripts/./periodlog.py", line 22, in <module>
    log = PeriodLog.fetch(telescope, period, **opts) 
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in fetch
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/periodlog.py", line 56, in <listcomp>
    logs = [NightLog.fetch(telescope, night, **opts)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/nightlog.py", line 67, in fetch
    log = query.fetch(night=night, use_tap_cache=use_tap_cache)
  File "/home/lachaume/git/autolog/scripts/../autolog/eso/tapquery.py", line 115, in fetch
    tab = tap.execute().to_table()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/tap.py", line 942, in execute
    return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 244, in execute_votable
    self.raise_if_error()
  File "/usr/local/lib/python3.10/dist-packages/pyvo/dal/query.py", line 253, in raise_if_error
    raise DALServiceError.from_except(e, self.queryurl)
pyvo.dal.exceptions.DALServiceError: 502 Server Error: Proxy Error for url: http://archive.eso.org/tap_obs/sync

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:34:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
github pull in /home/lachaume/git/autolog

daily.sh at 2023-03-13T16:35:01-03:00
-------------------------------------

error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
github pull in /home/lachaume/git/autolog

daily.sh at 2023-03-13T16:36:01-03:00
-------------------------------------

error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:37:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:38:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:39:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:40:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:41:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:42:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts
github pull in /home/lachaume/git/autolog

daily.sh at 2023-03-13T16:43:01-03:00
-------------------------------------

error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:44:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:45:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:46:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:47:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:48:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog

git add * in /home/lachaume/git/autolog
fatal: Unable to create '/home/lachaume/git/autolog/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git commit
git commit
fatal: Unable to create '/home/lachaume/git/autolog/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git push
git push

git add * in /home/lachaume/git/autolog
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

git commit

git add * in /home/lachaume/git/autolog
git push
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
git commit
To github.com:loqueelvientoajuarez/2.2m-website.git
 ! [remote rejected]   main -> main (cannot lock ref 'refs/heads/main': is at a7b07ee7d412dc25d8366c153c83993eea4bcea9 but expected 3fc79b16e886198fa1724e88a348fa533601bee7)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/2.2m-website.git'

To github.com:loqueelvientoajuarez/2.2m-website.git
   3fc79b16..a7b07ee7  main -> main


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog

git add * in /home/lachaume/git/autolog
fatal: Unable to create '/home/lachaume/git/autolog/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git commit
fatal: Unable to create '/home/lachaume/git/autolog/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git push
Everything up-to-date

git commit
git push

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
git commit

git add * in /home/lachaume/git/autolog
git commit
Everything up-to-date

git push

git add * in /home/lachaume/git/autolog
Everything up-to-date

git commit
git push
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
git commit

git add * in /data/www/twoptwo.com
git commit
Everything up-to-date

Everything up-to-date

Everything up-to-date


daily.sh at 2023-03-13T16:49:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:50:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:51:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
To github.com:loqueelvientoajuarez/2.2m-website.git
   a7b07ee7..73f397ba  main -> main


daily.sh at 2023-03-13T16:52:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:53:02-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:54:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:55:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

daily.sh at 2023-03-13T16:56:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

git add * in /home/lachaume/git/autolog

executing periodlog.py in /home/lachaume/git/autolog/scripts
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date

github pull in /home/lachaume/git/autolog

daily.sh at 2023-03-13T16:57:01-03:00
-------------------------------------

error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:58:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


daily.sh at 2023-03-13T16:59:01-03:00
-------------------------------------

github pull in /home/lachaume/git/autolog
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

github pull in /data/www/twoptwo.com

executing periodlog.py in /home/lachaume/git/autolog/scripts

git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /home/lachaume/git/autolog
git commit

git add * in /data/www/twoptwo.com
git commit
git push
Everything up-to-date

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit

git add * in /home/lachaume/git/autolog
git commit
git push
Everything up-to-date

To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
git commit
git push
To github.com:loqueelvientoajuarez/obslog.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:loqueelvientoajuarez/obslog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


git add * in /data/www/twoptwo.com
git commit
Everything up-to-date


git add * in /home/lachaume/git/autolog
